### PR TITLE
Miscellaneous modifications

### PR DESCRIPTION
**Pull request by countvajhula**
### Summary of changes

- Separate the notion of contained elements from the wrapping ring "segments"
  and don't expose the latter in external APIs
- Expand elementary data structure interface (constructors, accessors, etc.)
- API changes and additions, including:
	- `dyn-ring-values`
	- `dyn-ring-equal-p`
	- `dyn-ring-contains-p`
	- `dyn-ring-traverse-collect`
	- `dyn-ring-map`
	- `dyn-ring-transform-map`
	- `dyn-ring-filter`
	- `dyn-ring-transform-filter`
	- find forwards and backwards
	- deprecate `dyn-ring-find` for interface uniformity
	- distinguish "functional" and "mutating" interfaces
- "Break and recast" insertion to model recency
- Treat a 1-element ring as a trivial ring rather than as a non-ring
- Tests for all interfaces
- Remove deprecated cl dependency -> cl-lib
- Use lexical binding
- Build scripts and dev workflow
- Lint and checkdoc

### CODE REVIEW

**Comment by countvajhula** [comment]
I'd like to make the following requests as part of this PR @coderofmattie :

1. Change the license from GPL to public domain -- personally, I put all of the work I do into the public domain. I am working towards an attribution based economic system that will allow creators like ourselves to be recognized and empowered, where the basis of value is attribution rather than ownership. Public domain dedications allow the greatest possible value to be generated from source works, and the more projects that do this, the sooner such a system could become a reality. If you are on board with this (and I would greatly appreciate it), I will prepare the appropriate license file as part of this PR.

2. Make me a collaborator on the project. As you can see, I've made significant changes in the libraries, and it seems to make the most sense if I remain in a position to review and maintain these changes, which also lowers the commitment on both of us. It would be great for the project to benefit from our shared expertise, so we could in general submit pull requests so that we each have a chance to weigh in and improve the code.

WDYT?

**Comment by countvajhula** [comment]
What's the word @coderofmattie ? Just a friendly bump.

**Comment by bitcathedrals** [comment]
I really wanted to get into some lisp again, but I am in a startup nearing release. I just don’t have the time to tackle it. I looked at the patches after I forked the repository and I really liked it. The renaming of the parameters made a confusing section much more clear.

You have my blessing to take it over. I hope it goes far!!!

**Comment by countvajhula** [comment]
Ah, that's too bad @coderofmattie , but thank you for the blessing :) What do you think about the license change, though? Are you OK with changing it to public domain? It's just that I feel the most comfortable working on public domain work since, as I mentioned earlier, I put everything I do into the public domain and it makes it one less thing for me to worry about as I work on these things, and for that reason makes it much more likely that I'll freely and openly contribute to and improve these projects if they are "unlicensed." Besides the sentimental value of seeing the projects you started grow, there are other reasons for you to be interested in this:

If I may make another pitch for the public domain, the attribution system I'm working on means that the greater the value that is generated from work you do, the greater in commensurate measure is the recognition you receive for having contributed to that value. There is no need for ownership here -- just imagine, for a timely example, what it would mean if attribution alone could ensure that creative contributions (and contributors) receive their fair due. COVID vaccines, for instance, would not need to remain proprietary -- they are that way simply because that's necessary in supply-and-demand based capitalist economics in order to ensure that their creators remain in a position to be compensated. It's a sad state of affairs that these aren't done out in the open, and one that is entirely avoidable, and which may be remedied by the kind of attribution-based economics I'm talking about. Free software (and GPL), valiant an effort though it has been, cannot do this efficiently, even though it can bring things out in the open, because it is unable to incentivize creative contributions to the same extent that capitalism can. Attribution-based economics, on the other hand, can do it even more efficiently than capitalism - by perhaps an order of magnitude - by eliminating the traditional idea of ownership in favor of a less-strong yet more general notion of property.

I want to make clear that putting works into the public domain is not necessary for attribution-based economics to work for you -- all works past, present and future are of course in a position to be collectively recognized in terms of attribution, and they will be -- your work included. It's just that, when placed in the public domain, value you create compounds to the greatest possible extent, as a result of others (such as myself) openly contributing and innovating, knowing that they will be recognized by the same system that they recognize and not hindered by it. In essence, you create the most value by putting things in the public domain in an attribution based economy, and that in turn means you receive the most amount of recognition and empowerment, which someday would function like (and translate to) money.

Put your hat in the ring for a better way of doing things! What do you say, Mike? Do I have your permission to change the license to public domain?

Besides this, I'm obviously a fan of the work you did on dynamic-ring and buffer-ring. I would gladly list you as a contributor at the countvajhula fork, and you are welcome to contribute and participate to whatever extent you can. That way, you could return to Lisp on your own time.

Let me know, and thanks!

**Comment by bitcathedrals** [comment]
Please do put it in the public domain. I merely want to be mentioned as the creator
. Thanks for your patience with me. I have been very unusually busy privately and professionally and have not had the time I want to devote to it. I hope the code helps people and inspires other ideas.

Mike Mattie

On May 4, 2021 1:16:37 AM PDT, Siddhartha Kasivajhula ***@***.***> wrote:
>Ah, that's too bad @coderofmattie , but thank you for the blessing :)
>What do you think about the license change, though? Are you OK with
>changing it to public domain? It's just that I feel the most
>comfortable working on public domain work since, as I mentioned
>earlier, I put everything I do into the public domain and it makes it
>one less thing for me to worry about as I work on these things, and for
>that reason makes it much more likely that I'll freely and openly
>contribute to and improve these projects if they are "unlicensed."
>Besides the sentimental value of seeing the projects you started grow,
>there are other reasons for you to be interested in this:
>
>If I may make another pitch for the public domain, the attribution
>system I'm working on means that the greater the value that is
>generated from work you do, the greater in commensurate measure is the
>recognition you receive for having contributed to that value. There is
>no need for ownership here -- just imagine, for a timely example, what
>it would mean if attribution alone could ensure that creative
>contributions (and contributors) receive their fair due. COVID
>vaccines, for instance, would not need to remain proprietary -- they
>are that way simply because that's necessary in supply-and-demand based
>capitalist economics in order to ensure that their creators remain in a
>position to be compensated. It's a sad state of affairs that these
>aren't done out in the open, and one that is entirely avoidable, and
>which may be remedied by the kind of attribution-based economics I'm
>talking about. Free software (and GPL), valiant an effort though it has
>been, cannot do this efficiently, even though it can bring things out
>in the open, because it is unable to incentivize creative contributions
>to the same extent that capitalism can. Attribution-based economics, on
>the other hand, can do it even more efficiently than capitalism - by
>perhaps an order of magnitude - by eliminating the traditional idea of
>ownership in favor of a less-strong yet more general notion of
>property.
>
>I want to make clear that putting works into the public domain is not
>necessary for attribution-based economics to work for you -- all works
>past, present and future are of course in a position to be collectively
>recognized in terms of attribution, and they will be -- your work
>included. It's just that, when placed in the public domain, value you
>create compounds to the greatest possible extent, as a result of others
>(such as myself) openly contributing and innovating, knowing that they
>will be recognized by the same system that they recognize and not
>hindered by it. In essence, you create the most value by putting things
>in the public domain in an attribution based economy, and that in turn
>means you receive the most amount of recognition and empowerment, which
>someday would function like (and translate to) money.
>
>Put your hat in the ring for a better way of doing things! What do you
>say, Mike? Do I have your permission to change the license to public
>domain?
>
>Besides this, I'm obviously a fan of the work you did on dynamic-ring
>and buffer-ring. I would gladly list you as a contributor at the
>countvajhula fork, and you are welcome to contribute and participate to
>whatever extent you can. That way, you could return to Lisp on your own
>time.
>
>Let me know, and thanks!
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/coderofmattie/dynamic-ring/pull/1#issuecomment-831763488

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by countvajhula** [comment]
That's wonderful news Mike, you are a champion 😄  👍  🏆 . Stay tuned for updates on these packages, I will keep you in the loop. No worries on being busy, that's totally understandable!

**Comment by countvajhula** [comment]
@coderofmattie is there an updated email address I can use in the package author fields and any other places in the repo listing contributors? The listed gmail address bounced when I tried it a little while back, lmk.

**Comment by bitcathedrals** [comment]
***@***.*** pls! Thanks for the updates. I like following the progress.

Thanks
Mike Mattie

On May 12, 2021 9:47:54 PM PDT, Siddhartha Kasivajhula ***@***.***> wrote:
***@***.*** is there an updated email address I can use in the
>package author fields and any other places in the repo listing
>contributors? The listed gmail address bounced when I tried it a little
>while back, lmk.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/coderofmattie/dynamic-ring/pull/1#issuecomment-840294484

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by countvajhula** [comment]
@coderofmattie ah man, looks like GitHub blanks out the email address and it isn't visible in the UI -- maybe email it directly to my listed email in the repo?

**Comment by countvajhula** [comment]
I've added you as a collaborator on both repos, Mike, if you ever want to weigh in on anything that comes up or make contributions when you find time. I have no doubt that the projects could (continue to) benefit from your expertise :)

**Comment by countvajhula** [comment]
@coderofmattie just a reminder, could you email your updated email address to me at [this address](https://github.com/countvajhula/dynaring/blob/c800863b2ea51354882f56af6ff6fc8ccb50283a/dynaring.el#L4)? It didn't show up on the GitHub UI when you shared it earlier. Just want to make sure your contact info is up to date!

**Pull request closed without merging**
